name: 'ビルドできるか確認'

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 仮想ブランチにチェックアウト
        uses: actions/checkout@v3

      - name: Javaのセットアップ
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: ./gradlewに権限を付与
        run: |
          chmod 777 ${{ github.workspace }}/gradlew
      - name: ビルドを実行
        run: |
          ${{ github.workspace }}/gradlew build
